
data_path = "/Users/ekoch/storage/PHANGS/bubblezoo/images_for_zooniverse"
output_path = "/Users/ekoch/storage/PHANGS/bubblezoo/color_test_for_zooniverse_maxent_032025"

# Hydra runs
# data_path = "/home/erickoch/scratch/phangs_bubblezoo/images_for_zooniverse"
# output_path = "/home/erickoch/scratch/phangs_bubblezoo/color_test_for_zooniverse_geminicancer_maxent"

bands = [
    'f770w',  # jwst
    'f770w_cd',  # jwst with constrained diffusion
    'hst_bband',  # hst
]

targets = [
    # 'ic5332',
    # 'ngc0628',
    # 'ngc1300',
    # 'ngc1385',
    # 'ngc1512',
    # 'ngc1672',
    # 'ngc3351',
    # 'ngc4254',  ## has a header issue from my mosaicking
    'ngc4321',
    'ngc4826',
    'ngc7496',
    'ngc1087',
    # 'ngc1365',
    'ngc1433',
    'ngc1566',
    'ngc2835',
    'ngc3627',
    'ngc4303',
    'ngc4535',
    'ngc5068',
]


# There should be a parameters key for each band

[parameters.f770w]

file_search_str = '_F770W_starsub_anchored.fits'
hdu_ext = 0
apply_cd = false
apply_bkgsub = false
apply_radial_scaling = true

# Scale the galaxy center down if its radial profile exceeds this value.
# This is in whatever units this band is in.
radscale_thresh = 100

# 'yellow'
color = '#FFFF00'

[parameters.f770w.greyRGBize_kwargs]
rescalefn = 'asinh'
scaletype = 'maxent'

[parameters.f770w.colorize_image_kwargs]
colorintype = 'hex'
gammacorr_color = 2.2


[parameters.f770w_cd]

file_search_str = '_F770W_starsub_anchored.fits'
hdu_ext = 0
apply_cd = true
apply_bkgsub = false
apply_radial_scaling = true

# Scale the galaxy center down if its radial profile exceeds this value.
radscale_thresh = 100

# 'red ish'
color = '#FF0000'

[parameters.f770w_cd.greyRGBize_kwargs]
rescalefn = 'asinh'
scaletype = 'maxent'

[parameters.f770w_cd.colorize_image_kwargs]
colorintype = 'hex'
gammacorr_color = 2.2

[parameters.hst_bband]

file_search_str = 'wfc*_f4*w*exp-drc-sci.fits'  # F438W or F475W or F435W
hdu_ext = 0
hdu_ext_mask = 0
edge_clip = true  # Binary erosion along the edges
edge_clip_size = 60  # Number of binary erosion iterations
edge_clip_match = 'wfc3'  # instrument check. Only clip edges for wfc3

apply_cd = false
apply_bkgsub = true
apply_radial_scaling = false

bgksub_percent = 5.0

# cyan
color = '#00FFFF'


[parameters.hst_bband.greyRGBize_kwargs]
rescalefn = 'asinh'
scaletype = 'maxent'

[parameters.hst_bband.colorize_image_kwargs]
colorintype = 'hex'
gammacorr_color = 2.2
